package cartridge

const (
	FLAG_NO_FLAG = iota - 1
	FLAG_0_GARB_OFF
	FLAG_1_GARB_ON
	FLAG_2_WORD_CRICKET_BALL
	FLAG_3_WORD_MOTH
	FLAG_4_WORD_SOMETHING
	FLAG_5_WORD_ANOTHER
	FLAG_6_TERRY_HOUSE
	FLAG_7_TERI_HOUSE
	FLAG_8_STANDS
	FLAG_9_PUB
	FLAG_10_DEEP_FOREST
	FLAG_11_PUB_GOING_BEHIND_BAR
	FLAG_12_TERI_LENDING_BOOK
	FLAG_13_TERRY_PICTURE_ON_WALL
	FLAG_14_STATUE
	FLAG_15_LIBRARY
)

var (
	Flags = [16]int{}
)
